### ISSUE TITLE
Crash when opening quote

### ISSUE THREAD

**Issue by dalb8** [wakarimasenco/ChanExplorer#7]
I tapped a quote e.g. >>40303710 and to my surprise a new tab was opened instead of a modal dialog. I tapped the quote again the app crashed. Recent CM10.1 Nightly on p990.

```
02-14 13:59:25.310 E/AudioPolicyManagerBase(102): ********************************************************************************
02-14 13:59:25.320 E/AudioPolicyManagerBase(102): stopOutput() output 3, stream 3, session 282
02-14 13:59:25.320 E/AudioPolicyManagerBase(102): changeRefCount() stream 3, count 0
02-14 13:59:25.330 E/AudioPolicyManagerBase(102): getNewDevice() selected device 0
02-14 13:59:25.330 E/AudioPolicyManagerBase(102): setOutputDevice() output 3 device 0 delayMs 0
02-14 13:59:25.330 E/AudioPolicyManagerBase(102): setOutputDevice() setting same device 0 or null device for output 3 prevDevice=2
02-14 14:00:34.100 E/InputEventReceiver(28507): Exception dispatching input event.
02-14 14:00:34.100 E/MessageQueue-JNI(28507): Exception in MessageQueue callback: handleReceiveCallback
02-14 14:00:34.140 E/MessageQueue-JNI(28507): java.lang.NullPointerException
02-14 14:00:34.140 E/MessageQueue-JNI(28507):   at co.wakarimasen.chanexplorer.ThreadFragment.getHomeFragment(ThreadFragment.java:544)
02-14 14:00:34.140 E/MessageQueue-JNI(28507):   at co.wakarimasen.chanexplorer.ThreadFragment.gotoPost(ThreadFragment.java:589)
02-14 14:00:34.140 E/MessageQueue-JNI(28507):   at co.wakarimasen.chanexplorer.PostView$QuoteSpan.onClick(PostView.java:924)
02-14 14:00:34.140 E/MessageQueue-JNI(28507):   at android.text.method.LinkMovementMethod.onTouchEvent(LinkMovementMethod.java:212)
02-14 14:00:34.140 E/MessageQueue-JNI(28507):   at android.widget.TextView.onTouchEvent(TextView.java:7536)
02-14 14:00:34.140 E/MessageQueue-JNI(28507):   at android.view.View.dispatchTouchEvent(View.java:7253)
02-14 14:00:34.140 E/MessageQueue-JNI(28507):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
02-14 14:00:34.140 E/MessageQueue-JNI(28507):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
02-14 14:00:34.140 E/MessageQueue-JNI(28507):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
02-14 14:00:34.140 E/MessageQueue-JNI(28507):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
02-14 14:00:34.140 E/MessageQueue-JNI(28507):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
02-14 14:00:34.140 E/MessageQueue-JNI(28507):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
02-14 14:00:34.140 E/MessageQueue-JNI(28507):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
02-14 14:00:34.140 E/MessageQueue-JNI(28507):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
02-14 14:00:34.140 E/MessageQueue-JNI(28507):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
02-14 14:00:34.140 E/MessageQueue-JNI(28507):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
02-14 14:00:34.140 E/MessageQueue-JNI(28507):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
02-14 14:00:34.140 E/MessageQueue-JNI(28507):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
02-14 14:00:34.140 E/MessageQueue-JNI(28507):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
02-14 14:00:34.140 E/MessageQueue-JNI(28507):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
02-14 14:00:34.140 E/MessageQueue-JNI(28507):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
02-14 14:00:34.140 E/MessageQueue-JNI(28507):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
02-14 14:00:34.140 E/MessageQueue-JNI(28507):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
02-14 14:00:34.140 E/MessageQueue-JNI(28507):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
02-14 14:00:34.140 E/MessageQueue-JNI(28507):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
02-14 14:00:34.140 E/MessageQueue-JNI(28507):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
02-14 14:00:34.140 E/MessageQueue-JNI(28507):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
02-14 14:00:34.140 E/MessageQueue-JNI(28507):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
02-14 14:00:34.140 E/MessageQueue-JNI(28507):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
02-14 14:00:34.140 E/MessageQueue-JNI(28507):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
02-14 14:00:34.140 E/MessageQueue-JNI(28507):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
02-14 14:00:34.140 E/MessageQueue-JNI(28507):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
02-14 14:00:34.140 E/MessageQueue-JNI(28507):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
02-14 14:00:34.140 E/MessageQueue-JNI(28507):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
02-14 14:00:34.140 E/MessageQueue-JNI(28507):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
02-14 14:00:34.140 E/MessageQueue-JNI(28507):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
02-14 14:00:34.140 E/MessageQueue-JNI(28507):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
02-14 14:00:34.140 E/MessageQueue-JNI(28507):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
02-14 14:00:34.140 E/MessageQueue-JNI(28507):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
02-14 14:00:34.140 E/MessageQueue-JNI(28507):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
02-14 14:00:34.140 E/MessageQueue-JNI(28507):   at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2215)
02-14 14:00:34.140 E/MessageQueue-JNI(28507):   at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1458)
02-14 14:00:34.140 E/MessageQueue-JNI(28507):   at android.app.Activity.dispatchTouchEvent(Activity.java:2410)
02-14 14:00:34.140 E/MessageQueue-JNI(28507):   at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2163)
02-14 14:00:34.140 E/MessageQueue-JNI(28507):   at android.view.View.dispatchPointerEvent(View.java:7433)
02-14 14:00:34.140 E/MessageQueue-JNI(28507):   at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3220)
02-14 14:00:34.140 E/MessageQueue-JNI(28507):   at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3165)
02-14 14:00:34.140 E/MessageQueue-JNI(28507):   at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4292)
02-14 14:00:34.140 E/MessageQueue-JNI(28507):   at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4271)
02-14 14:00:34.140 E/MessageQueue-JNI(28507):   at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4363)
02-14 14:00:34.140 E/MessageQueue-JNI(28507):   at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:179)
02-14 14:00:34.140 E/MessageQueue-JNI(28507):   at android.os.MessageQueue.nativePollOnce(Native Method)
02-14 14:00:34.140 E/MessageQueue-JNI(28507):   at android.os.MessageQueue.next(MessageQueue.java:125)
02-14 14:00:34.140 E/MessageQueue-JNI(28507):   at android.os.Looper.loop(Looper.java:124)
02-14 14:00:34.140 E/MessageQueue-JNI(28507):   at android.app.ActivityThread.main(ActivityThread.java:52
02-14 14:00:34.150 W/dalvikvm(28507): threadid=1: thread exiting with uncaught exception (group=0x41210930)
02-14 14:00:34.150 E/AndroidRuntime(28507): FATAL EXCEPTION: main
02-14 14:00:34.150 E/AndroidRuntime(28507): java.lang.NullPointerException
02-14 14:00:34.150 E/AndroidRuntime(28507):     at co.wakarimasen.chanexplorer.ThreadFragment.getHomeFragment(ThreadFragment.java:544)
02-14 14:00:34.150 E/AndroidRuntime(28507):     at co.wakarimasen.chanexplorer.ThreadFragment.gotoPost(ThreadFragment.java:589)
02-14 14:00:34.150 E/AndroidRuntime(28507):     at co.wakarimasen.chanexplorer.PostView$QuoteSpan.onClick(PostView.java:924)
02-14 14:00:34.150 E/AndroidRuntime(28507):     at android.text.method.LinkMovementMethod.onTouchEvent(LinkMovementMethod.java:212)
02-14 14:00:34.150 E/AndroidRuntime(28507):     at android.widget.TextView.onTouchEvent(TextView.java:7536)
02-14 14:00:34.150 E/AndroidRuntime(28507):     at android.view.View.dispatchTouchEvent(View.java:7253)
02-14 14:00:34.150 E/AndroidRuntime(28507):     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
02-14 14:00:34.150 E/AndroidRuntime(28507):     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
02-14 14:00:34.150 E/AndroidRuntime(28507):     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
02-14 14:00:34.150 E/AndroidRuntime(28507):     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
02-14 14:00:34.150 E/AndroidRuntime(28507):     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
02-14 14:00:34.150 E/AndroidRuntime(28507):     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
02-14 14:00:34.150 E/AndroidRuntime(28507):     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
02-14 14:00:34.150 E/AndroidRuntime(28507):     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
02-14 14:00:34.150 E/AndroidRuntime(28507):     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
02-14 14:00:34.150 E/AndroidRuntime(28507):     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
02-14 14:00:34.150 E/AndroidRuntime(28507):     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
02-14 14:00:34.150 E/AndroidRuntime(28507):     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
02-14 14:00:34.150 E/AndroidRuntime(28507):     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
02-14 14:00:34.150 E/AndroidRuntime(28507):     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
02-14 14:00:34.150 E/AndroidRuntime(28507):     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
02-14 14:00:34.150 E/AndroidRuntime(28507):     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
02-14 14:00:34.150 E/AndroidRuntime(28507):     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
02-14 14:00:34.150 E/AndroidRuntime(28507):     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
02-14 14:00:34.150 E/AndroidRuntime(28507):     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
02-14 14:00:34.150 E/AndroidRuntime(28507):     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
02-14 14:00:34.150 E/AndroidRuntime(28507):     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
02-14 14:00:34.150 E/AndroidRuntime(28507):     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
02-14 14:00:34.150 E/AndroidRuntime(28507):     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
02-14 14:00:34.150 E/AndroidRuntime(28507):     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
02-14 14:00:34.150 E/AndroidRuntime(28507):     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
02-14 14:00:34.150 E/AndroidRuntime(28507):     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
02-14 14:00:34.150 E/AndroidRuntime(28507):     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
02-14 14:00:34.150 E/AndroidRuntime(28507):     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
02-14 14:00:34.150 E/AndroidRuntime(28507):     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
02-14 14:00:34.150 E/AndroidRuntime(28507):     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
02-14 14:00:34.150 E/AndroidRuntime(28507):     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
02-14 14:00:34.150 E/AndroidRuntime(28507):     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
02-14 14:00:34.150 E/AndroidRuntime(28507):     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
02-14 14:00:34.150 E/AndroidRuntime(28507):     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
02-14 14:00:34.150 E/AndroidRuntime(28507):     at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2215)
02-14 14:00:34.150 E/AndroidRuntime(28507):     at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1458)
02-14 14:00:34.150 E/AndroidRuntime(28507):     at android.app.Activity.dispatchTouchEvent(Activity.java:2410)
02-14 14:00:34.150 E/AndroidRuntime(28507):     at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2163)
02-14 14:00:34.150 E/AndroidRuntime(28507):     at android.view.View.dispatchPointerEvent(View.java:7433)
02-14 14:00:34.150 E/AndroidRuntime(28507):     at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3220)
02-14 14:00:34.150 E/AndroidRuntime(28507):     at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3165)
02-14 14:00:34.150 E/AndroidRuntime(28507):     at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4292)
02-14 14:00:34.150 E/AndroidRuntime(28507):     at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4271)
02-14 14:00:34.150 E/AndroidRuntime(28507):     at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4363)
02-14 14:00:34.150 E/AndroidRuntime(28507):     at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:179)
02-14 14:00:34.150 E/AndroidRuntime(28507):     at android.os.MessageQueue.nativePollOnce(Native Method)
02-14 14:00:34.150 E/AndroidRuntime(28507):     at android.os.MessageQueue.next(MessageQueue.java:125)
02-14 14:00:34.150 E/AndroidRuntime(28507):     at android.os.Looper.loop(Looper.java:124)
02-14 14:00:34.150 E/AndroidRuntime(28507):     at android.app.ActivityThread.main(Ac
02-14 14:00:34.170 W/ActivityManager(375):   Force finishing activity co.wakarimasen.chanexplorer/.MainActivity
02-14 14:00:34.680 W/ActivityManager(375): Activity pause timeout for ActivityRecord{41552480 u0 co.wakarimasen.chanexplorer/.MainActivity}
02-14 14:00:35.270 W/ActivityManager(375): Scheduling restart of crashed service net.i2p.android.router/.service.RouterService in 5000ms
02-14 14:00:40.330 W/Trace   (28540): error opening trace file: No such file or directory (2)
02-14 14:00:42.250 W/Trace   (28555): error opening trace file: No such file or directory (2)
02-14 14:00:42.540 E/su      (28575): sqlite3_exec: callback requested query abort 
02-14 14:00:42.560 W/su      (28578): request rejected (10086->0 /system/bin/sh) 
02-14 14:00:43.470 W/Trace   (28591): error opening trace file: No such file or directory (2)
02-14 14:01:00.240 W/InputMethodManagerService(375): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@41a276f0 attribute=null, token = android.os.BinderProxy@41bba9a0

```

**Comment by dalb8** [comment]
Eh, maybe it opened a new tab because I were on the home page.
